import 'package:flutterapp/models/post_model.dart';

List<Post> dummyPosts = [
  Post(
    id: 1,
    title: '전주 한옥마을 여행 후기',
    content: '전주 한옥마을에서 즐거운 시간을 보냈습니다. 한복 체험도 하고 맛있는 먹거리도 많았어요!',
    author: '여행자1',
    views: 150,
    likes: 15,
    createdAt: '2024-07-15',
    category: '자유 게시판',
    tags: ['전주', '가족여행', '먹거리'],
  ),
  Post(
    id: 2,
    title: '서울 야경이 보이는 힐링 카페',
    content: '남산 타워 근처 카페에서 야경을 보며 힐링했습니다. 커피도 맛있고 분위기도 최고!',
    author: '카페탐방가',
    views: 220,
    likes: 25,
    createdAt: '2024-07-16',
    category: '자유 게시판',
    tags: ['서울', '힐링', '카페'],
  ),
  Post(
    id: 3,
    title: '광명 동굴로 아이들과 함께하는 탐험',
    content: '아이들과 광명 동굴에 다녀왔어요. 동굴 속 테마파크가 신기해서 아이들이 정말 좋아했어요!',
    author: '육아대디',
    views: 95,
    likes: 8,
    createdAt: '2024-07-17',
    category: '행사 게시판',
    tags: ['광명', '아이들', '가족여행'],
  ),
  Post(
    id: 4,
    title: '가평 잣나무 숲 산책로',
    content: '피톤치드 가득한 가평 잣나무 숲에서 산책을 즐겼습니다. 공기가 정말 맑아요!',
    author: '자연인',
    views: 180,
    likes: 20,
    createdAt: '2024-07-18',
    category: '팝업 게시판',
    tags: ['가평', '산책', '힐링'],
  ),
  Post(
    id: 5,
    title: '청주 맛집 투어',
    content: '청주에서 유명한 맛집들을 방문했어요. 특히 쫄면 맛이 일품입니다.',
    author: '미식가',
    views: 250,
    likes: 30,
    createdAt: '2024-07-19',
    category: '자유 게시판',
    tags: ['청주', '먹거리'],
  ),
  Post(
    id: 6,
    title: '서울 여행 꿀팁',
    content: '서울에 방문할 때 꼭 가봐야 할 장소들을 정리해봤어요.',
    author: '서울시민',
    views: 300,
    likes: 45,
    createdAt: '2024-07-20',
    category: '자유 게시판',
    tags: ['서울', '여행'],
  ),
  Post(
    id: 7,
    title: '가족과 함께 하는 주말',
    content: '가족과 함께 보드게임 하면서 즐거운 주말을 보냈습니다.',
    author: '행복이',
    views: 110,
    likes: 12,
    createdAt: '2024-07-21',
    category: '자유 게시판',
    tags: ['가족', '주말'],
  ),
  Post(
    id: 8,
    title: '광명 벚꽃 축제',
    content: '광명에서 벚꽃 축제가 열리고 있습니다. 이번 주말까지라고 하니 서둘러서 가보세요!',
    author: '축제알리미',
    views: 50,
    likes: 5,
    createdAt: '2024-07-22',
    category: '행사 게시판',
    tags: ['광명', '벚꽃', '행사'],
  ),
];
